language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install mypy ujson
script:
- mypy Facebook --ignore-missing-imports
deploy:
  provider: pypi
  user:
    secure: rEOR/Vj7qO9Vi94yPjkvdtLJl46lk6IgSLsO9fbIeoYXBMKxdfeUdmPmHvwG/3xtE6/I3oN2fi20xoEF0DDUxXSRo68DjcsJxB4ImcJAHkuJsQtHCzrdUTumLA2wTQxGnBr0WM/fxs4rf4ONUQjJfO8Y/62Cq3d1OxOe/ObPb4Zk8vtJf+7gwGlm+n+7AHeJz7MDFvuWWdxuiji8aEqBR4DQIqMSgttiXQRPvaJSCbVQIMG0NzbA8rtYdiEX7L0UZ3v2n3FTwL7Al432h1Ai6EmakjVE95maYZcvFElXTjQ5Ach5zbkBHL4tbYw3NXSSTFvRyKKuZQreJXPArJ76QSsRYG4Sn5HQ92VOjK2CrOlYKdD1b/al3YxEZO5UhicpZBJnrniljtGyAZcUAsJqjYMNWqLJqSj+RkzBz1qoxsqG7e0pd8o73/p5TZhi/FKsPcFvM4WDpmF4jQTIfJ7Z8H3smn3j6WE5oxp05E+eBhSrpWh50NeTzm7AJ+a98zafvGSI3IRg41PLvEcKQIn4Jz9Cs/iiqrTJqD9V03DvxelB6eK+Prm1RNyccd3cMy3nDZ1Yo4kq7Xzum+CvdtVPe1CAPkNxc1Nutd63f94rju6rvqj25/ZN0xf9k82F8Eyom6F0ppZNTyn+yCI8mAiigdiTYY6HQYmZe16TxzZITNA=
  password:
    secure: htVdzSS31SuYJfnPK0a38LAK3MFS/n8YIZnShGvALp/eYO5doOOgFpcCyM9jamlP7qwhmKDHSFA0r0VEORHVw/UPNxKU4cbyOQQVEJUl561kbIIt1JHr6V2CLdrDpOMQXMGgcTu9UcfqbOYqm/n4KpYcPBdJ56d6Z0y/UjkCq1+rUTkumxXsuv736lXAb5/hI8fmGW5n6POnQr81Yv6iaL1EPx/lxruZVNIBL+s4nwlk/8GERvPGpF2Kok3WQ3Krx8HFkf4gwP+FBs0Zmobd8jOUCAUkcPrwLkR/CRGxPFRewIQmGJzq36pX8jDKOWvqkghPGBvdP6zQnFdcVWed2/kB9OdBEYgMCqU8ZQ7VuVh3thhniBftOR/H5Fveobnqq+Tzjo7Blet3N2NsoDJfF+ZoNW55SBFYFvFMSR9UvqZB0938XlXIOcbqsaskwp/q+BFDH4+R7zdZtoYcBbyT36ekbp9TMo2WPzymyH0z165ep3+J6Xc1GzIDyYnE+F/F2V1FrVrzHfULzQFc60SVb4yBqEyyvQgdGjlO/ats/aNV+trESIQCzBYb03JkJd62emvnTd43wxPkxhVieIrmP6OKKd0UG1/ZS4rNnFcu/3WNi750HG0jJmLeW8Nhfm0Q78U23/Hdb4NIhR+/ONaryaYah8LWyrTesSCdrq1a1P0=
