language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install mypy ujson pytest
script:
- mypy Facebook --ignore-missing-imports
- pytest tests
deploy:
  provider: pypi
  user:
    secure: rEOR/Vj7qO9Vi94yPjkvdtLJl46lk6IgSLsO9fbIeoYXBMKxdfeUdmPmHvwG/3xtE6/I3oN2fi20xoEF0DDUxXSRo68DjcsJxB4ImcJAHkuJsQtHCzrdUTumLA2wTQxGnBr0WM/fxs4rf4ONUQjJfO8Y/62Cq3d1OxOe/ObPb4Zk8vtJf+7gwGlm+n+7AHeJz7MDFvuWWdxuiji8aEqBR4DQIqMSgttiXQRPvaJSCbVQIMG0NzbA8rtYdiEX7L0UZ3v2n3FTwL7Al432h1Ai6EmakjVE95maYZcvFElXTjQ5Ach5zbkBHL4tbYw3NXSSTFvRyKKuZQreJXPArJ76QSsRYG4Sn5HQ92VOjK2CrOlYKdD1b/al3YxEZO5UhicpZBJnrniljtGyAZcUAsJqjYMNWqLJqSj+RkzBz1qoxsqG7e0pd8o73/p5TZhi/FKsPcFvM4WDpmF4jQTIfJ7Z8H3smn3j6WE5oxp05E+eBhSrpWh50NeTzm7AJ+a98zafvGSI3IRg41PLvEcKQIn4Jz9Cs/iiqrTJqD9V03DvxelB6eK+Prm1RNyccd3cMy3nDZ1Yo4kq7Xzum+CvdtVPe1CAPkNxc1Nutd63f94rju6rvqj25/ZN0xf9k82F8Eyom6F0ppZNTyn+yCI8mAiigdiTYY6HQYmZe16TxzZITNA=
  password:
    secure: VMunHTQzifZxmyzU0Phg/ZKLMueVotQjVMZ8/6JuU2ankGoHlq2+p0xeZ49bYVBwDVuZIX0/fH7hqJmjrMa8Aw4IM2YwNyk1AT2OV7XA3gmGWXTSUlgQ4EL7w74Ehrtl8iKiEIDgApLXJdRMzJnhkC0VV34T0tHKuUkUGVwxuL8TMjmxfuBlmtzZEB+sSs1YkxnKJl++KlPNoT+vn1T5jOm3pnphv4xDSmdT81LmwcAVryXGsGqs6jqyeiT5y4iFEQXqS+WSRi8ZJPEHZbfYSdMTj+PqHibNXIdyBvKkDz5oOX40cz0wbVARH+GDYgQTJQ5z0Ihs02qmIP2rmYaXyzNVugsy/8YTs1xxdc8VvPkqk4p9M3Seqg+evNr180IvDsdAWlQ7nxi/KTRAx6sWmpEXEN4LhGL+IxDuAOCkOW2TWDZkIiP+DKWLLYFhQpxnlW/So4MFmO02Ao3Xo5IZ3iU84uyOr8bGilAHRhPfoedYIfSG589XFEJsmsfCP2SFsU/T+CWp8AuZe4ulh6tw1X0dENSPsjdCZcdhsb4qQOTAEBx+N0fx5EKXFA5TBD7QYmzu7h/rWs0V0jmsmLiAM71RrUYf+11Mj3HGHIXeGEE5/iwq0Kws9+H5VNOyVNgdEfzeR5ooXb6zUP/ieymsuOJVolyy2EHg+CIoRVgStZI=
